# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-25 14:02
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reacts',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('react', models.NullBooleanField()),
                ('timestamp', models.DateTimeField(null=True)),
                ('userstatus', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('fk_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.Posts')),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reacts',
                'managed': True,
            },
        ),
    ]
