# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-26 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reacts',
            name='userstatus',
        ),
    ]
